os: linux
language: python
python:
  - "3.7"

install:
  - pip install -U platformio

script:
  - pio ci examples/basic_demo/basic_demo.ino --lib ./ --board nodemcuv2
  - pio ci examples/basic_demo/basic_demo.ino --lib ./ --board nanoatmega328
